### ISSUE TITLE
How to disable white shadow around Window?

### ISSUE THREAD

**Issue by wolf-yuan-6115** [vinceliuice/Jasper-gtk-theme#23]
Is there an option to disable white shadow around windows border?

![image](https://github.com/vinceliuice/Jasper-gtk-theme/assets/58245644/3cc1e3fb-410c-4b03-9c01-87d4e4e8c84a)

**Comment by animaldaydream** [comment]
I got this bug by passing `--tweaks macos` to the installer script. The only workaround for me was to not pass that option.

Your screenshot is not showing that tweak though.

I'm using https://aur.archlinux.org/packages/libadwaita-without-adwaita-git rather than the regular libadwaita as finding the actual file which takes the GTK_THEME environment variable is too troublesome. It's too late at night to test though, sorry.

**Comment by wolf-yuan-6115** [comment]
> I got this bug by passing `--tweaks macos` to the installer script. The only workaround for me was to not pass that option.
> 
> Your screenshot is not showing that tweak though.
> 
> I'm using https://aur.archlinux.org/packages/libadwaita-without-adwaita-git rather than the regular libadwaita as finding the actual file which takes the GTK_THEME environment variable is too troublesome. It's too late at night to test though, sorry.

I didn't pass anything to the install script, weird.

**Comment by jbdrthapa** [comment]
If I exclude the following commit I don't see this issue. https://github.com/vinceliuice/Jasper-gtk-theme/commit/5f697349fc905b1a4ea7787c543ef32d24e7deec
